version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - ${APP_PORT}:22
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local